import {
  LayoutDashboard,
  Route as RouteIcon,
  Search,
  AlertTriangle,
  TrendingUp,
  Clock,
  Bus,
  Ruler,
  ShieldCheck,
  RefreshCw,
  Play,
  CheckCircle2,
  XCircle,
  Target,
  Info,
  GitBranch,
  Image as ImageIcon,
  Loader2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Filter,
  Download,
  Eye,
  Inbox,
  AlertCircle,
  Calendar,
  Activity,
  Database,
  FileText,
  BarChart3,
  PieChart as PieChartIcon,
  LineChart as LineChartIcon,
  Camera,
  Sparkles,
} from 'lucide-react'

const ICONS = {
  'layout-dashboard': LayoutDashboard,
  'route': RouteIcon,
  'search': Search,
  'alert-triangle': AlertTriangle,
  'trending-up': TrendingUp,
  'clock': Clock,
  'bus': Bus,
  'ruler': Ruler,
  'shield-check': ShieldCheck,
  'refresh': RefreshCw,
  'play': Play,
  'check': CheckCircle2,
  'x-circle': XCircle,
  'target': Target,
  'info': Info,
  'git-branch': GitBranch,
  'image': ImageIcon,
  'loader': Loader2,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'x': X,
  'filter': Filter,
  'download': Download,
  'eye': Eye,
  'inbox': Inbox,
  'alert-circle': AlertCircle,
  'calendar': Calendar,
  'activity': Activity,
  'database': Database,
  'file-text': FileText,
  'bar-chart': BarChart3,
  'pie-chart': PieChartIcon,
  'line-chart': LineChartIcon,
  'camera': Camera,
  'sparkles': Sparkles,
}

const SIZES = { sm: 14, md: 16, lg: 20, xl: 24 }

export default function Icon({ name, size = 'md', className = '', strokeWidth = 1.75, ...rest }) {
  const Cmp = ICONS[name]
  if (!Cmp) return null
  const px = typeof size === 'number' ? size : SIZES[size] || 16
  return <Cmp size={px} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...rest} />
}
